import { useState, useEffect, useRef } from "react";
import { supabase } from "./supabase.js";

const USERS = [
  { id: "pranav", name: "Pranav", avatar: "🧑‍💻", color: "#FF6B35" },
  { id: "kesha", name: "Kesha", avatar: "💃", color: "#E040FB" },
];
const DEFAULT_CATEGORIES = {
  income: [{ name:"Salary",emoji:"💰" },{ name:"Freelance",emoji:"💻" },{ name:"Gift",emoji:"🎁" },{ name:"Refund",emoji:"🔄" },{ name:"Other Income",emoji:"📥" }],
  expense: [{ name:"Groceries",emoji:"🛒" },{ name:"Eating Out",emoji:"🍕" },{ name:"Transport",emoji:"🚌" },{ name:"Shopping",emoji:"🛍️" },{ name:"Bills",emoji:"📄" },{ name:"Rent",emoji:"🏠" },{ name:"Entertainment",emoji:"🎬" },{ name:"Health",emoji:"💊" },{ name:"Education",emoji:"📚" },{ name:"Subscriptions",emoji:"📱" },{ name:"Gifts",emoji:"🎀" },{ name:"Travel",emoji:"✈️" },{ name:"Pets",emoji:"🐾" },{ name:"Savings",emoji:"🏦" },{ name:"Other",emoji:"📦" }],
};
const THEMES = { sunset:{name:"Sunset",g1:"#FF6B35",g2:"#FF8F00",accent:"#E040FB"}, ocean:{name:"Ocean",g1:"#0EA5E9",g2:"#2563EB",accent:"#06B6D4"}, forest:{name:"Forest",g1:"#16A34A",g2:"#15803D",accent:"#84CC16"}, berry:{name:"Berry",g1:"#C026D3",g2:"#9333EA",accent:"#F472B6"}, midnight:{name:"Midnight",g1:"#6366F1",g2:"#4338CA",accent:"#818CF8"} };
const EMOJI_OPTS = ["🍔","🏋️","🎮","☕","🍺","💇","🧹","🚗","📦","🎵","👶","💐","🏥","📱","🎓","✨","🔧","🐶","🎁","💰"];
const TIPS = ["Try a no-spend day once a week 💪","Round up purchases and save the difference","Unsubscribe from one unused service","Cook at home twice more this week 🍳","Wait 24h before any purchase over £30","Pack lunch — saves ~£200/month","Check subscriptions you forgot about","Set weekly limits, not just monthly","50/30/20 rule: needs/wants/savings","Try a cash-only week","Compare prices before buying over £20","Batch errands to save transport 🚌","Review your budget every Sunday"];
const MO = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const fmt = n => "£"+Math.abs(n).toFixed(2);
const mk = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
const td = () => new Date().toISOString().split("T")[0];

// Supabase helpers
async function fetchTx(){const{data,error}=await supabase.from("transactions").select("*").order("created_at",{ascending:false});if(error)return[];return data.map(r=>({id:r.id,userId:r.user_id,type:r.type,category:r.category,emoji:r.emoji,amount:parseFloat(r.amount),note:r.note||"",date:r.date,recurring:r.recurring,sg:r.split_group_id,stotal:r.split_total?parseFloat(r.split_total):null,paidBy:r.paid_by||null,receiptUrl:r.receipt_url||null}))}
async function insertTx(tx){await supabase.from("transactions").insert({user_id:tx.userId,type:tx.type,category:tx.category,emoji:tx.emoji,amount:tx.amount,note:tx.note,date:tx.date,recurring:tx.recurring,split_group_id:tx.sg||null,split_total:tx.stotal||null,paid_by:tx.paidBy||null,receipt_url:tx.receiptUrl||null})}
async function updateTx(id,f){const m={};if(f.amount!==undefined)m.amount=f.amount;if(f.note!==undefined)m.note=f.note;if(f.date!==undefined)m.date=f.date;await supabase.from("transactions").update(m).eq("id",id)}
async function uploadReceipt(file){const p=`receipts/${Date.now()}_${Math.random().toString(36).slice(2)}.${file.name.split('.').pop()}`;const{error}=await supabase.storage.from("receipts").upload(p,file);if(error)return null;return supabase.storage.from("receipts").getPublicUrl(p).data?.publicUrl||null}
async function deleteTxById(id){await supabase.from("transactions").delete().eq("id",id)}
async function deleteTxByGroup(gid){await supabase.from("transactions").delete().eq("split_group_id",gid)}
async function getS(key,fb){try{const{data,error}=await supabase.from("settings").select("value").eq("key",key).single();if(error||!data)return fb;let v=data.value;if(typeof v==='string')try{v=JSON.parse(v)}catch{};if(typeof v==='string')try{v=JSON.parse(v)}catch{};return v}catch{return fb}}
async function setS(key,val){await supabase.from("settings").upsert({key,value:val,updated_at:new Date().toISOString()})}

function AnimNum({value}){const[d,setD]=useState(value);const r=useRef();useEffect(()=>{let s=d,e=value,st=null;const go=ts=>{if(!st)st=ts;let p=Math.min((ts-st)/450,1);p=1-Math.pow(1-p,3);setD(s+(e-s)*p);if(p<1)r.current=requestAnimationFrame(go)};r.current=requestAnimationFrame(go);return()=>cancelAnimationFrame(r.current)},[value]);return<>£{Math.abs(d).toFixed(2)}</>}
function Donut({data,size=115}){if(!data.length)return null;const total=data.reduce((s,d)=>s+d.value,0);const pal=["#FF6B35","#E040FB","#00BFA5","#FFB300","#42A5F5","#EF5350","#AB47BC","#66BB6A"];let acc=0;const cx=size/2,cy=size/2,rad=size*0.37,sw=size*0.15;return<div style={{position:"relative",width:size,height:size,flexShrink:0}}><svg width={size} height={size}>{data.map((d,i)=>{const pct=d.value/total,start=acc;acc+=pct;const a1=start*2*Math.PI-Math.PI/2,a2=(start+pct)*2*Math.PI-Math.PI/2;return<path key={i} d={`M ${cx+rad*Math.cos(a1)} ${cy+rad*Math.sin(a1)} A ${rad} ${rad} 0 ${pct>0.5?1:0} 1 ${cx+rad*Math.cos(a2)} ${cy+rad*Math.sin(a2)}`} fill="none" stroke={pal[i%pal.length]} strokeWidth={sw} strokeLinecap="round" style={{animation:`dd 0.8s ease ${i*0.08}s both`}}/>})}</svg><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:size*0.12,fontWeight:700,fontFamily:"'Fraunces',serif"}}>{fmt(total)}</span></div></div>}
function BarChart({data,color,maxVal}){const mx=maxVal||Math.max(...data.map(d=>d.value),1);return<div style={{display:"flex",alignItems:"flex-end",gap:3,height:100,padding:"0 4px"}}>{data.map((d,i)=><div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:2}}><span style={{fontSize:8,fontWeight:600,opacity:0.7}}>{d.value>0?fmt(d.value):""}</span><div style={{width:"100%",maxWidth:28,borderRadius:4,background:color,opacity:d.value>0?0.8:0.15,height:`${Math.max((d.value/mx)*70,2)}px`,animation:`bg 0.6s ease ${i*0.05}s both`}}/><span style={{fontSize:8,opacity:0.5}}>{d.label}</span></div>)}</div>}

export default function App(){
  const[ready,setReady]=useState(false);const[locked,setLocked]=useState(true);const[pinInput,setPinInput]=useState("");const[pinError,setPinError]=useState(false);const[storedPin,setStoredPin]=useState(null);const[settingPin,setSettingPin]=useState(false);const[newPin,setNewPin]=useState("");const[confirmPin,setConfirmPin]=useState("");
  const[txs,setTxs]=useState([]);const[budget,setBudget]=useState(1500);const[dark,setDark]=useState(false);const[theme,setTheme]=useState("sunset");const[customCats,setCustomCats]=useState({income:[],expense:[]});
  const[curUser,setCurUser]=useState("pranav");const[filter,setFilter]=useState("all");const[month,setMonth]=useState(mk(new Date()));const[view,setView]=useState("home");
  const[txType,setTxType]=useState("expense");const[cat,setCat]=useState(null);const[amt,setAmt]=useState("");const[note,setNote]=useState("");const[date,setDate]=useState(td());const[recurring,setRecurring]=useState(false);const[split,setSplit]=useState("solo");
  const[toast,setToast]=useState(null);const[delId,setDelId]=useState(null);const[editBgt,setEditBgt]=useState(false);const[bgtIn,setBgtIn]=useState("1500");const[showSplits,setShowSplits]=useState(false);const[saving,setSaving]=useState(false);const[settleHistory,setSettleHistory]=useState([]);
  const[newCatName,setNewCatName]=useState("");const[newCatEmoji,setNewCatEmoji]=useState("📦");const[newCatType,setNewCatType]=useState("expense");const[showEmojiPicker,setShowEmojiPicker]=useState(false);
  const[convFrom,setConvFrom]=useState("GBP");const[convTo,setConvTo]=useState("EUR");const[convAmt,setConvAmt]=useState("");const[convResult,setConvResult]=useState(null);const[convLoading,setConvLoading]=useState(false);
  const[receiptFile,setReceiptFile]=useState(null);const[receiptPreview,setReceiptPreview]=useState(null);const[viewingReceipt,setViewingReceipt]=useState(null);
  const[budgetAlert,setBudgetAlert]=useState(null);const[alertDismissed,setAlertDismissed]=useState(false);
  const[searchQuery,setSearchQuery]=useState("");const[searchCat,setSearchCat]=useState("all");
  const[editingTx,setEditingTx]=useState(null);const[editAmt,setEditAmt]=useState("");const[editNote,setEditNote]=useState("");const[editDate,setEditDate]=useState("");
  const[lastDeleted,setLastDeleted]=useState(null);const[undoTimer,setUndoTimer]=useState(null);
  const[goals,setGoals]=useState([]);const[wishlist,setWishlist]=useState([]);
  const[newGoalName,setNewGoalName]=useState("");const[newGoalTarget,setNewGoalTarget]=useState("");const[newGoalEmoji,setNewGoalEmoji]=useState("🎯");
  const[newWishName,setNewWishName]=useState("");const[newWishPrice,setNewWishPrice]=useState("");const[newWishEmoji,setNewWishEmoji]=useState("✨");

  useEffect(()=>{(async()=>{const[t,b,d,th,cc,sh,pin,gl,wl]=await Promise.all([fetchTx(),getS("monthly_budget",1500),getS("dark_mode",false),getS("theme","sunset"),getS("custom_categories",{income:[],expense:[]}),getS("settle_history",[]),getS("app_pin",null),getS("savings_goals",[]),getS("wishlist",[])]);setTxs(t);setBudget(parseFloat(b)||1500);setBgtIn(String(parseFloat(b)||1500));setDark(d===true||d==="true");setTheme((typeof th==='string'&&THEMES[th])?th:"sunset");setCustomCats(cc&&typeof cc==='object'?cc:{income:[],expense:[]});setSettleHistory(Array.isArray(sh)?sh:[]);setStoredPin(pin?String(pin):null);setGoals(Array.isArray(gl)?gl:[]);setWishlist(Array.isArray(wl)?wl:[]);if(!pin){setLocked(false);setSettingPin(true)};setReady(true)})()},[]);
  useEffect(()=>{const ch=supabase.channel("bb-rt").on("postgres_changes",{event:"*",schema:"public",table:"transactions"},async()=>setTxs(await fetchTx())).on("postgres_changes",{event:"*",schema:"public",table:"settings"},async()=>{setBudget(parseFloat(await getS("monthly_budget",1500))||1500);setDark((await getS("dark_mode",false))===true)}).subscribe();return()=>supabase.removeChannel(ch)},[]);

  const flash=(msg,type="success")=>{setToast({msg,type});setTimeout(()=>setToast(null),2400)};
  const allCats={income:[...DEFAULT_CATEGORIES.income,...(customCats.income||[])],expense:[...DEFAULT_CATEGORIES.expense,...(customCats.expense||[])]};
  const th=THEMES[theme]||THEMES.sunset;
  const c=dark?{bg:"#0D0D14",card:"#161622",ca:"#1C1C2A",p:th.g1,pg:`${th.g1}18`,inc:"#34D399",ig:"rgba(52,211,153,0.09)",exp:"#F87171",eg:"rgba(248,113,113,0.09)",tx:"#EEEEF2",sf:"#8585A0",mu:"#50506A",bd:"#252535",ac:th.accent,ag:`${th.accent}18`,sh:"0 3px 14px rgba(0,0,0,0.3)",g1:th.g1,g2:th.g2}:{bg:"#F4F1EA",card:"#FFFFFF",ca:"#FFF8F0",p:th.g1,pg:`${th.g1}0F`,inc:"#16A34A",ig:"rgba(22,163,74,0.06)",exp:"#DC2626",eg:"rgba(220,38,38,0.06)",tx:"#1A1A2E",sf:"#6B6B80",mu:"#A0A0B4",bd:"#E5E1D9",ac:th.accent,ag:`${th.accent}0F`,sh:"0 2px 8px rgba(0,0,0,0.035)",g1:th.g1,g2:th.g2};

  const mTx=txs.filter(x=>x.date.startsWith(month)&&(filter==="all"||x.userId===filter));
  const totI=mTx.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0);const totE=mTx.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0);const bal=totI-totE;const bPct=budget>0?Math.min((totE/budget)*100,100):0;
  const ebc={};mTx.filter(x=>x.type==="expense").forEach(x=>{ebc[x.category]=(ebc[x.category]||0)+x.amount});const sExp=Object.entries(ebc).sort((a,b)=>b[1]-a[1]);
  const uStats=USERS.map(u=>{const ut=txs.filter(x=>x.date.startsWith(month)&&x.userId===u.id);return{...u,exp:ut.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0)}});
  const splitGrps={};mTx.filter(x=>x.sg).forEach(x=>{if(!splitGrps[x.sg])splitGrps[x.sg]=[];splitGrps[x.sg].push(x)});const splitKeys=Object.keys(splitGrps);
  const splitDebts={};txs.filter(x=>x.date.startsWith(month)&&x.sg&&x.paidBy).forEach(tx=>{if(!splitDebts[tx.sg])splitDebts[tx.sg]={paidBy:tx.paidBy,total:tx.stotal||tx.amount*2,half:tx.amount,emoji:tx.emoji,category:tx.category,note:tx.note,date:tx.date}});
  let runBal=0;const debtItems=[];Object.entries(splitDebts).forEach(([gid,d])=>{if(d.paidBy==="pranav")runBal+=d.half;else runBal-=d.half;debtItems.push({...d,gid,owes:d.paidBy==="pranav"?"kesha":"pranav",amount:d.half})});
  settleHistory.filter(s=>s.month===month).forEach(s=>{if(s.from==="kesha")runBal-=s.amount;else runBal+=s.amount});
  const settleAmt=Math.abs(runBal);const whoOwes=runBal>0?"kesha":"pranav";const whoIsOwed=runBal>0?"pranav":"kesha";
  const filteredTx=mTx.filter(tx=>{if(searchCat!=="all"&&tx.category!==searchCat)return false;if(searchQuery){const q=searchQuery.toLowerCase();return tx.category.toLowerCase().includes(q)||tx.note.toLowerCase().includes(q)||String(tx.amount).includes(q)}return true});
  const calcStreak=()=>{const today=new Date();let s=0;for(let i=0;i<365;i++){const d=new Date(today);d.setDate(d.getDate()-i);if(txs.some(x=>x.date===d.toISOString().split("T")[0]))s++;else break}return s};
  const streak=calcStreak();const todayTip=TIPS[new Date().getDate()%TIPS.length];
  const reportData=()=>{const ms=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const key=mk(d);const mt=txs.filter(x=>x.date.startsWith(key));ms.push({label:MO[d.getMonth()],income:mt.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expense:mt.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0)})}return ms};

  const navM=d=>{const[y,m]=month.split("-").map(Number);setMonth(mk(new Date(y,m-1+d)))};const[cy,cm]=month.split("-").map(Number);const mLabel=`${MO[cm-1]} ${cy}`;const isNow=month===mk(new Date());
  const reset=()=>{setCat(null);setAmt("");setNote("");setDate(td());setRecurring(false);setSplit("solo");setReceiptFile(null);setReceiptPreview(null)};
  const toggleDark=async()=>{setDark(!dark);await setS("dark_mode",!dark)};const saveBgt=async v=>{setBudget(v);setEditBgt(false);await setS("monthly_budget",v)};const changeTheme=async t=>{setTheme(t);await setS("theme",t)};
  const verifyPin=input=>{if(String(input)===String(storedPin)){setLocked(false);setPinInput("");setPinError(false)}else{setPinError(true);setPinInput("");setTimeout(()=>setPinError(false),1500)}};
  const saveNewPin=async()=>{if(newPin.length<4){flash("Min 4 digits","error");return}if(newPin!==confirmPin){flash("PINs don't match!","error");return}const p=String(newPin);await setS("app_pin",p);setStoredPin(p);setSettingPin(false);setNewPin("");setConfirmPin("");setLocked(false);flash("PIN set! 🔐")};
  const removePin=async()=>{await setS("app_pin",null);setStoredPin(null);flash("PIN removed")};
  const addCustomCat=async()=>{if(!newCatName.trim())return;const u={...customCats};if(!u[newCatType])u[newCatType]=[];u[newCatType].push({name:newCatName.trim(),emoji:newCatEmoji});setCustomCats(u);await setS("custom_categories",u);setNewCatName("");flash("Added! ✨")};
  const removeCustomCat=async(type,name)=>{const u={...customCats};u[type]=u[type].filter(c=>c.name!==name);setCustomCats(u);await setS("custom_categories",u)};
  const settleUp=async()=>{const e={date:new Date().toISOString(),month,amount:settleAmt,from:whoOwes,to:whoIsOwed};const u=[...settleHistory,e];setSettleHistory(u);await setS("settle_history",u);flash("Settled! 🎉")};
  const handleReceipt=e=>{const f=e.target.files?.[0];if(!f||f.size>5*1024*1024)return;setReceiptFile(f);const r=new FileReader();r.onload=ev=>setReceiptPreview(ev.target.result);r.readAsDataURL(f)};
  const exportCSV=()=>{const rows=mTx.map(tx=>[tx.date,USERS.find(u=>u.id===tx.userId)?.name,tx.type,tx.category,tx.amount.toFixed(2),`"${tx.note}"`,tx.sg?"Yes":"No"]);const csv=["Date,Who,Type,Category,Amount,Note,Split",...rows.map(r=>r.join(","))].join("\n");const b=new Blob([csv],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`budget-${month}.csv`;a.click();flash("Downloaded! 📥")};
  const CURRENCIES=[{code:"GBP",flag:"🇬🇧"},{code:"EUR",flag:"🇪🇺"},{code:"USD",flag:"🇺🇸"},{code:"INR",flag:"🇮🇳"},{code:"JPY",flag:"🇯🇵"},{code:"AUD",flag:"🇦🇺"},{code:"CAD",flag:"🇨🇦"},{code:"CHF",flag:"🇨🇭"},{code:"AED",flag:"🇦🇪"},{code:"TRY",flag:"🇹🇷"},{code:"THB",flag:"🇹🇭"},{code:"PLN",flag:"🇵🇱"}];
  const convert=async()=>{if(!convAmt)return;setConvLoading(true);try{const r=await fetch(`https://api.exchangerate-api.com/v4/latest/${convFrom}`);const d=await r.json();const rate=d.rates[convTo];if(rate)setConvResult({amount:parseFloat(convAmt)*rate,rate})}catch{flash("Failed","error")}setConvLoading(false)};
  const addTx=async()=>{if(!cat||!amt||parseFloat(amt)<=0){flash("Fill in details!","error");return}setSaving(true);const raw=parseFloat(parseFloat(amt).toFixed(2));let rUrl=null;if(receiptFile)rUrl=await uploadReceipt(receiptFile);const base={type:txType,category:cat.name,emoji:cat.emoji,note:note.trim(),date,recurring,receiptUrl:rUrl};if(split==="split"){const h=parseFloat((raw/2).toFixed(2));const gid=`s_${Date.now()}`;await insertTx({...base,userId:"pranav",amount:h,sg:gid,stotal:raw,paidBy:curUser});await insertTx({...base,userId:"kesha",amount:h,sg:gid,stotal:raw,paidBy:curUser});flash(`${USERS.find(u=>u.id===curUser)?.name} paid ${fmt(raw)} 🤝`)}else{await insertTx({...base,userId:curUser,amount:raw});flash(txType==="income"?"Added! 🎉":"Logged! ✅")}setTxs(await fetchTx());setSaving(false);reset();setView("home")};
  const startEdit=tx=>{setEditingTx(tx);setEditAmt(String(tx.amount));setEditNote(tx.note);setEditDate(tx.date)};
  const saveEdit=async()=>{if(!editingTx)return;setSaving(true);await updateTx(editingTx.id,{amount:parseFloat(editAmt),note:editNote,date:editDate});setTxs(await fetchTx());setEditingTx(null);setSaving(false);flash("Updated! ✏️")};
  const delTx=async id=>{const tx=txs.find(x=>x.id===id);setLastDeleted(tx);setDelId(null);if(tx?.sg)setTxs(p=>p.filter(x=>x.sg!==tx.sg));else setTxs(p=>p.filter(x=>x.id!==id));flash("Deleted — tap undo bar below","info");if(undoTimer)clearTimeout(undoTimer);setUndoTimer(setTimeout(async()=>{if(tx?.sg)await deleteTxByGroup(tx.sg);else await deleteTxById(id);setLastDeleted(null)},5000))};
  const undoDelete=async()=>{if(!lastDeleted)return;if(undoTimer)clearTimeout(undoTimer);setTxs(await fetchTx());setLastDeleted(null);flash("Restored! ↩️")};
  const addGoal=async()=>{if(!newGoalName||!newGoalTarget)return;const g=[...goals,{id:Date.now(),name:newGoalName,target:parseFloat(newGoalTarget),saved:0,emoji:newGoalEmoji}];setGoals(g);await setS("savings_goals",g);setNewGoalName("");setNewGoalTarget("");flash("Goal created! 🎯")};
  const updateGoalSaved=async(id,amt)=>{const g=goals.map(x=>x.id===id?{...x,saved:Math.max(0,x.saved+amt)}:x);setGoals(g);await setS("savings_goals",g)};
  const deleteGoal=async id=>{const g=goals.filter(x=>x.id!==id);setGoals(g);await setS("savings_goals",g)};
  const addWish=async()=>{if(!newWishName)return;const w=[...wishlist,{id:Date.now(),name:newWishName,price:parseFloat(newWishPrice)||0,emoji:newWishEmoji,addedBy:curUser,done:false}];setWishlist(w);await setS("wishlist",w);setNewWishName("");setNewWishPrice("");flash("Added! ✨")};
  const toggleWish=async id=>{const w=wishlist.map(x=>x.id===id?{...x,done:!x.done}:x);setWishlist(w);await setS("wishlist",w)};
  const deleteWish=async id=>{const w=wishlist.filter(x=>x.id!==id);setWishlist(w);await setS("wishlist",w)};

  useEffect(()=>{if(!ready||alertDismissed)return;const cm=mk(new Date());const ct=txs.filter(x=>x.date.startsWith(cm)&&x.type==="expense").reduce((s,x)=>s+x.amount,0);const p=budget>0?(ct/budget)*100:0;if(p>=100)setBudgetAlert({msg:`Over budget by ${fmt(ct-budget)}!`,color:"#DC2626",emoji:"🚨"});else if(p>=90)setBudgetAlert({msg:`${Math.round(p)}% used — ${fmt(budget-ct)} left!`,color:"#DC2626",emoji:"⚠️"});else if(p>=75)setBudgetAlert({msg:`${Math.round(p)}% spent`,color:"#F59E0B",emoji:"📊"});else setBudgetAlert(null)},[txs,budget,ready,alertDismissed]);

  const B={border:"none",borderRadius:13,cursor:"pointer",fontFamily:"'DM Sans',sans-serif",fontWeight:600,transition:"all 0.17s"};const C={background:c.card,borderRadius:18,padding:"15px 16px",boxShadow:c.sh,border:`1px solid ${c.bd}`};

  if(!ready)return<div style={{fontFamily:"'DM Sans',sans-serif",background:"#F4F1EA",minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center"}}><p style={{fontSize:40}}>💸</p></div>;

  if(locked&&storedPin)return(<div style={{fontFamily:"'DM Sans',sans-serif",background:`linear-gradient(135deg,${th.g1},${th.g2})`,minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><style>{`*{box-sizing:border-box;margin:0;padding:0}@keyframes shake{0%,100%{transform:translateX(0)}25%{transform:translateX(-8px)}50%{transform:translateX(8px)}}`}</style><div style={{textAlign:"center",maxWidth:320,width:"100%"}}><p style={{fontSize:48,marginBottom:12}}>🔐</p><h1 style={{fontFamily:"'Fraunces',serif",fontSize:24,fontWeight:800,color:"#fff",marginBottom:28}}>Budget Buddy</h1><div style={{display:"flex",justifyContent:"center",gap:10,marginBottom:20,animation:pinError?"shake 0.4s":"none"}}>{[0,1,2,3].map(i=><div key={i} style={{width:16,height:16,borderRadius:"50%",background:pinInput.length>i?"#fff":"rgba(255,255,255,0.3)"}}/>)}</div>{pinError&&<p style={{color:"#FEE2E2",fontSize:12,marginBottom:12}}>Wrong PIN</p>}<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,maxWidth:240,margin:"0 auto"}}>{[1,2,3,4,5,6,7,8,9,null,0,"⌫"].map((n,i)=>n===null?<div key={i}/>:<button key={i} onClick={()=>{if(n==="⌫")setPinInput(p=>p.slice(0,-1));else if(pinInput.length<4){const next=pinInput+String(n);setPinInput(next);if(next.length===4)setTimeout(()=>verifyPin(next),150)}}} style={{width:"100%",aspectRatio:"1",borderRadius:16,border:"none",background:"rgba(255,255,255,0.15)",color:"#fff",fontSize:22,fontWeight:600,fontFamily:"'DM Sans',sans-serif",cursor:"pointer"}}>{n}</button>)}</div></div></div>);

  if(settingPin)return(<div style={{fontFamily:"'DM Sans',sans-serif",background:c.bg,color:c.tx,minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",padding:20}}><style>{`*{box-sizing:border-box;margin:0;padding:0}input:focus{outline:none}`}</style><div style={{textAlign:"center",maxWidth:320,width:"100%"}}><p style={{fontSize:40,marginBottom:10}}>🔐</p><h2 style={{fontFamily:"'Fraunces',serif",fontSize:20,fontWeight:800,marginBottom:24}}>{storedPin?"Change PIN":"Set a PIN"}</h2><div style={{marginBottom:14}}><input value={newPin} onChange={e=>setNewPin(e.target.value.replace(/\D/g,""))} type="password" inputMode="numeric" maxLength={8} placeholder="New PIN" style={{width:200,border:`2px solid ${c.bd}`,borderRadius:12,padding:"12px 16px",fontSize:22,color:c.tx,background:c.card,textAlign:"center",letterSpacing:8,fontFamily:"'DM Sans',sans-serif"}}/></div><div style={{marginBottom:20}}><input value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,""))} type="password" inputMode="numeric" maxLength={8} placeholder="Confirm" style={{width:200,border:`2px solid ${newPin&&confirmPin&&newPin!==confirmPin?c.exp:c.bd}`,borderRadius:12,padding:"12px 16px",fontSize:22,color:c.tx,background:c.card,textAlign:"center",letterSpacing:8,fontFamily:"'DM Sans',sans-serif"}}/></div><div style={{display:"flex",gap:8,justifyContent:"center"}}>{storedPin&&<button onClick={()=>setSettingPin(false)} style={{...B,padding:"11px 20px",fontSize:13,background:c.bd,color:c.tx}}>Cancel</button>}<button onClick={saveNewPin} style={{...B,padding:"11px 24px",fontSize:13,background:`linear-gradient(135deg,${c.g1},${c.g2})`,color:"#fff"}}>{storedPin?"Update":"Set PIN"}</button></div>{!storedPin&&<button onClick={()=>{setSettingPin(false);setLocked(false)}} style={{...B,background:"none",color:c.mu,fontSize:11,marginTop:14}}>Skip →</button>}</div></div>);

  // ═══ MAIN APP ═══
  return(<div style={{fontFamily:"'DM Sans',sans-serif",background:c.bg,color:c.tx,minHeight:"100vh",maxWidth:480,margin:"0 auto",position:"relative",transition:"background 0.3s,color 0.3s"}}><style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600;9..40,700&family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700;9..144,800&display=swap');*{box-sizing:border-box;margin:0;padding:0}html,body{overscroll-behavior:none}input:focus,button:focus{outline:none}input[type=number]::-webkit-inner-spin-button{-webkit-appearance:none}input[type=number]{-moz-appearance:textfield}::-webkit-scrollbar{width:0}@keyframes su{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}@keyframes fi{from{opacity:0}to{opacity:1}}@keyframes pi{from{opacity:0;transform:scale(0.92)}to{opacity:1;transform:scale(1)}}@keyframes sd{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}@keyframes bg{from{width:0}}@keyframes dd{from{stroke-dasharray:0 1000}to{stroke-dasharray:1000 1000}}@keyframes gl{0%,100%{box-shadow:0 0 14px ${c.g1}20}50%{box-shadow:0 0 24px ${c.g1}55}}.h{transition:all 0.14s}.h:hover{transform:translateY(-1px)}.h:active{transform:scale(0.97)}`}</style>

    {toast&&<div style={{position:"fixed",top:12,left:"50%",transform:"translateX(-50%)",background:toast.type==="error"?c.exp:toast.type==="info"?"#3B82F6":c.inc,color:"#fff",padding:"9px 18px",borderRadius:13,fontWeight:600,fontSize:12,zIndex:1000,animation:"sd 0.3s",boxShadow:c.sh,maxWidth:"86%"}}>{toast.msg}</div>}
    {lastDeleted&&<div onClick={undoDelete} style={{position:"fixed",bottom:70,left:"50%",transform:"translateX(-50%)",background:"#1F1F1F",color:"#fff",padding:"10px 18px",borderRadius:12,fontWeight:600,fontSize:12,zIndex:999,cursor:"pointer",boxShadow:"0 4px 16px rgba(0,0,0,0.3)",animation:"su 0.3s",display:"flex",alignItems:"center",gap:8}}><span>↩️ Tap to undo delete</span></div>}

    {/* HOME */}
    {view==="home"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.25s"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div><h1 style={{fontFamily:"'Fraunces',serif",fontSize:22,fontWeight:800}}>Budget Buddy</h1><p style={{color:c.sf,fontSize:10.5,marginTop:1}}>Pranav & Kesha 💕</p></div><div style={{display:"flex",gap:5}}><button onClick={()=>setView("settings")} className="h" style={{...B,width:38,height:38,borderRadius:11,background:c.ca,border:`1px solid ${c.bd}`,fontSize:16}}>⚙️</button><button onClick={toggleDark} className="h" style={{...B,width:38,height:38,borderRadius:11,background:c.ca,border:`1px solid ${c.bd}`,fontSize:16}}>{dark?"☀️":"🌙"}</button></div></div>

      {streak>0&&<div style={{...C,marginBottom:10,padding:"11px 14px",display:"flex",alignItems:"center",gap:10,animation:"su 0.2s"}}><span style={{fontSize:22}}>🔥</span><div style={{flex:1}}><p style={{fontSize:11,fontWeight:600}}>{streak} day streak!</p><p style={{fontSize:9.5,color:c.sf,marginTop:1}}>{todayTip}</p></div></div>}
      {budgetAlert&&!alertDismissed&&isNow&&<div style={{...C,marginBottom:10,borderLeft:`3px solid ${budgetAlert.color}`,padding:"12px 14px",display:"flex",alignItems:"center",gap:10,animation:"su 0.25s"}}><span style={{fontSize:20}}>{budgetAlert.emoji}</span><div style={{flex:1}}><p style={{fontSize:11,fontWeight:600,color:budgetAlert.color}}>Budget Alert</p><p style={{fontSize:10,color:c.sf}}>{budgetAlert.msg}</p></div><button onClick={()=>setAlertDismissed(true)} style={{...B,background:"none",fontSize:14,color:c.mu}}>×</button></div>}

      <div style={{display:"flex",gap:5,marginBottom:12}}>{[{id:"all",name:"Together",avatar:"👫",color:c.p},...USERS].map(u=><button key={u.id} className="h" onClick={()=>setFilter(u.id)} style={{...B,flex:1,padding:"8px 4px",borderRadius:12,fontSize:10.5,background:filter===u.id?(dark?c.ca:u.color+"10"):c.card,border:filter===u.id?`2px solid ${u.color}`:`1px solid ${c.bd}`,color:filter===u.id?u.color:c.sf}}><span style={{fontSize:14,display:"block",marginBottom:1}}>{u.avatar}</span>{u.name}</button>)}</div>
      <div style={{display:"flex",justifyContent:"center",alignItems:"center",gap:10,marginBottom:12}}><button onClick={()=>navM(-1)} className="h" style={{...B,width:30,height:30,borderRadius:9,background:c.card,border:`1px solid ${c.bd}`,fontSize:12,color:c.tx}}>‹</button><span style={{fontWeight:600,fontSize:13.5,minWidth:80,textAlign:"center"}}>{mLabel}</span><button onClick={()=>navM(1)} className="h" style={{...B,width:30,height:30,borderRadius:9,background:isNow?c.bg:c.card,border:`1px solid ${c.bd}`,fontSize:12,color:isNow?c.mu:c.tx}} disabled={isNow}>›</button></div>

      <div style={{background:`linear-gradient(135deg,${c.g1},${c.g2})`,borderRadius:20,padding:"22px 18px",color:"#fff",boxShadow:`0 7px 24px ${c.g1}33`,marginBottom:10,animation:"su 0.35s"}}><p style={{fontSize:10,opacity:0.8,marginBottom:2}}>{filter==="all"?"Combined":USERS.find(u=>u.id===filter)?.name+"'s"} Balance</p><p style={{fontFamily:"'Fraunces',serif",fontSize:32,fontWeight:800,letterSpacing:-1,marginBottom:14}}>{bal<0?"−":""}<AnimNum value={Math.abs(bal)}/></p><div style={{display:"flex",gap:7}}><div style={{flex:1,background:"rgba(255,255,255,0.15)",borderRadius:12,padding:"8px 9px"}}><p style={{fontSize:9,opacity:0.7}}>↑ Income</p><p style={{fontSize:15,fontWeight:700}}><AnimNum value={totI}/></p></div><div style={{flex:1,background:"rgba(255,255,255,0.15)",borderRadius:12,padding:"8px 9px"}}><p style={{fontSize:9,opacity:0.7}}>↓ Spent</p><p style={{fontSize:15,fontWeight:700}}><AnimNum value={totE}/></p></div></div></div>

      <div style={{...C,marginBottom:10,animation:"su 0.4s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:11.5,fontWeight:600}}>Budget</span>{!editBgt?<button onClick={()=>{setEditBgt(true);setBgtIn(String(budget))}} style={{...B,background:"none",fontSize:10.5,color:c.p}}>{fmt(budget)} ✎</button>:<div style={{display:"flex",gap:3,alignItems:"center"}}><input value={bgtIn} onChange={e=>setBgtIn(e.target.value)} type="number" autoFocus style={{width:60,border:`2px solid ${c.p}`,borderRadius:7,padding:"2px 4px",fontSize:11,background:c.bg,color:c.tx,fontFamily:"'DM Sans',sans-serif"}}/><button onClick={()=>{const v=parseFloat(bgtIn);if(v>0)saveBgt(v)}} style={{...B,background:c.p,color:"#fff",padding:"2px 6px",fontSize:10,borderRadius:7}}>✓</button></div>}</div><div style={{height:6,background:c.bd,borderRadius:6,overflow:"hidden"}}><div style={{height:"100%",borderRadius:6,animation:"bg 0.7s",width:`${bPct}%`,background:bPct>90?c.exp:bPct>70?"#F59E0B":c.inc,transition:"width 0.5s"}}/></div><p style={{fontSize:9.5,color:c.sf,marginTop:3}}>{fmt(totE)} / {fmt(budget)}{bPct>=100?" 🚨":""}</p></div>

      {filter==="all"&&<><div style={{display:"flex",gap:7,marginBottom:10,animation:"su 0.45s"}}>{uStats.map(u=><div key={u.id} style={{...C,flex:1,padding:"11px 10px",textAlign:"center",borderLeft:`3px solid ${u.color}`}}><span style={{fontSize:18}}>{u.avatar}</span><p style={{fontSize:10.5,fontWeight:600,marginTop:2}}>{u.name}</p><p style={{fontSize:13,fontWeight:700,fontFamily:"'Fraunces',serif",color:c.exp,marginTop:2}}>{fmt(u.exp)}</p></div>)}</div>
        {settleAmt>0.01&&<div style={{...C,marginBottom:10,borderLeft:"3px solid #F59E0B",padding:"13px 15px",animation:"su 0.47s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{fontSize:11.5,fontWeight:600}}>⚖️ {USERS.find(u=>u.id===whoOwes)?.name} owes {USERS.find(u=>u.id===whoIsOwed)?.name}</p><p style={{fontFamily:"'Fraunces',serif",fontSize:20,fontWeight:800,marginTop:2}}>{fmt(settleAmt)}</p></div><button className="h" onClick={settleUp} style={{...B,background:"#F59E0B",color:"#fff",padding:"9px 14px",borderRadius:10,fontSize:11}}>Settle</button></div></div>}
      </>}

      {goals.length>0&&<div style={{...C,marginBottom:10,animation:"su 0.49s"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><h3 style={{fontSize:11.5,fontWeight:600}}>🎯 Goals</h3><button onClick={()=>setView("goals")} style={{...B,background:"none",fontSize:10,color:c.p}}>All →</button></div>{goals.slice(0,2).map(g=><div key={g.id} style={{marginBottom:6}}><div style={{display:"flex",justifyContent:"space-between",fontSize:10,marginBottom:3}}><span>{g.emoji} {g.name}</span><span style={{fontWeight:600}}>{fmt(g.saved)}/{fmt(g.target)}</span></div><div style={{height:5,background:c.bd,borderRadius:5,overflow:"hidden"}}><div style={{height:"100%",borderRadius:5,background:g.saved>=g.target?c.inc:c.p,width:`${Math.min((g.saved/g.target)*100,100)}%`}}/></div></div>)}</div>}

      <div style={{display:"flex",gap:5,marginBottom:10,animation:"su 0.52s",flexWrap:"wrap"}}>{[["📊","Reports","report"],["💱","Convert","convert"],["📥","CSV",null],["🎯","Goals","goals"],["💫","Wishlist","wishlist"],["🔍","Search","search"]].map(([e,l,v],i)=><button key={i} className="h" onClick={v?()=>setView(v):exportCSV} style={{...B,...C,flex:"1 1 30%",padding:"10px 6px",textAlign:"center",fontSize:10}}>{e} {l}</button>)}</div>

      {sExp.length>0&&<div style={{...C,marginBottom:10,animation:"su 0.5s"}}><h3 style={{fontSize:11.5,fontWeight:600,marginBottom:10}}>Spending</h3><div style={{display:"flex",alignItems:"center",gap:12}}><Donut data={sExp.map(([n,v])=>({name:n,value:v}))} size={108}/><div style={{flex:1}}>{sExp.slice(0,6).map(([ct,am],i)=>{const co=allCats.expense.find(x=>x.name===ct);const pal=["#FF6B35","#E040FB","#00BFA5","#FFB300","#42A5F5","#EF5350"];return<div key={ct} style={{display:"flex",alignItems:"center",gap:4,marginBottom:4}}><div style={{width:6,height:6,borderRadius:3,background:pal[i%pal.length]}}/><span style={{fontSize:10,color:c.sf,flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{co?.emoji} {ct}</span><span style={{fontSize:10,fontWeight:600}}>{fmt(am)}</span></div>})}</div></div></div>}

      <div style={{...C,animation:"su 0.55s"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><h3 style={{fontSize:11.5,fontWeight:600}}>Recent</h3>{mTx.length>5&&<button onClick={()=>setView("history")} style={{...B,background:"none",fontSize:10,color:c.p}}>All →</button>}</div>
        {mTx.length===0?<div style={{textAlign:"center",padding:"20px 0"}}><p style={{fontSize:28}}>📝</p><p style={{color:c.sf,fontSize:11}}>No transactions</p></div>
        :mTx.slice(0,6).map((tx,i)=>{const u=USERS.find(u=>u.id===tx.userId);return<div key={tx.id} style={{display:"flex",alignItems:"center",gap:8,padding:"7px 0",borderBottom:i<5?`1px solid ${c.bd}`:"none"}}><span style={{width:34,height:34,borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,flexShrink:0,background:tx.type==="income"?c.ig:c.eg}}>{tx.emoji}</span><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:3}}><p style={{fontSize:11.5,fontWeight:500}}>{tx.category}</p>{tx.sg&&<span style={{fontSize:7.5,background:c.ag,color:c.ac,padding:"0.5px 3.5px",borderRadius:4,fontWeight:600}}>Split</span>}{tx.receiptUrl&&<span onClick={()=>setViewingReceipt(tx.receiptUrl)} style={{fontSize:9,cursor:"pointer",background:c.pg,padding:"1px 5px",borderRadius:4,color:c.p,fontWeight:600}}>📷</span>}</div><p style={{fontSize:8.5,color:c.mu,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{u?.avatar} {u?.name} · {new Date(tx.date).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}{tx.note?` · ${tx.note}`:""}</p></div><p style={{fontSize:12.5,fontWeight:600,flexShrink:0,color:tx.type==="income"?c.inc:c.exp}}>{tx.type==="income"?"+":"−"}{fmt(tx.amount)}</p><button onClick={()=>startEdit(tx)} style={{...B,background:"none",fontSize:10,color:c.mu}}>✏️</button></div>})}
      </div>
    </div>}

    {/* ADD */}
    {view==="add"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>{setView("home");reset()}} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>New Transaction</h2></div>
      <div style={{...C,marginBottom:8,padding:"11px 13px"}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:6,color:c.sf}}>Who?</p><div style={{display:"flex",gap:6}}>{USERS.map(u=><button key={u.id} className="h" onClick={()=>setCurUser(u.id)} style={{...B,flex:1,padding:"8px 4px",borderRadius:11,fontSize:11,background:curUser===u.id?(dark?c.ca:u.color+"10"):"transparent",border:curUser===u.id?`2px solid ${u.color}`:`1px solid ${c.bd}`,color:curUser===u.id?u.color:c.sf}}>{u.avatar} {u.name}</button>)}</div></div>
      <div style={{display:"flex",background:c.card,borderRadius:12,padding:2.5,border:`1px solid ${c.bd}`,marginBottom:8}}>{["expense","income"].map(t=><button key={t} onClick={()=>{setTxType(t);setCat(null);setSplit("solo")}} style={{...B,flex:1,padding:"9px 0",fontSize:11.5,borderRadius:10,background:txType===t?(t==="expense"?c.exp:c.inc):"transparent",color:txType===t?"#fff":c.sf}}>{t==="expense"?"💸 Expense":"💰 Income"}</button>)}</div>
      <div style={{...C,marginBottom:8,textAlign:"center",padding:"18px 14px"}}><p style={{fontSize:9.5,color:c.sf,marginBottom:4}}>Amount</p><div style={{display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:24,fontWeight:700,fontFamily:"'Fraunces',serif",color:c.sf}}>£</span><input value={amt} onChange={e=>setAmt(e.target.value)} type="number" placeholder="0.00" inputMode="decimal" style={{fontSize:36,fontWeight:800,fontFamily:"'Fraunces',serif",border:"none",background:"transparent",textAlign:"center",color:c.tx,width:"60%"}}/></div>{txType==="expense"&&<div style={{display:"flex",justifyContent:"center",gap:5,marginTop:7}}>{[{id:"solo",l:"Just me"},{id:"split",l:"Split 🤝"}].map(o=><button key={o.id} className="h" onClick={()=>setSplit(o.id)} style={{...B,padding:"4px 10px",borderRadius:8,fontSize:10.5,background:split===o.id?c.ag:"transparent",border:split===o.id?`2px solid ${c.ac}`:`1px solid ${c.bd}`,color:split===o.id?c.ac:c.sf}}>{o.l}</button>)}</div>}{split==="split"&&amt&&<p style={{fontSize:9.5,color:c.ac,marginTop:4}}>Each: {fmt(parseFloat(amt||0)/2)}</p>}</div>
      <div style={{...C,marginBottom:8}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:7}}>Category</p><div style={{display:"flex",flexWrap:"wrap",gap:4}}>{allCats[txType].map(ct=><button key={ct.name} className="h" onClick={()=>setCat(ct)} style={{...B,padding:"5px 10px",fontSize:10.5,borderRadius:8,background:cat?.name===ct.name?(txType==="income"?c.ig:c.eg):(dark?c.ca:c.bd+"80"),color:cat?.name===ct.name?(txType==="income"?c.inc:c.exp):c.sf,border:cat?.name===ct.name?`2px solid ${txType==="income"?c.inc:c.exp}`:"2px solid transparent"}}>{ct.emoji} {ct.name}</button>)}</div></div>
      <div style={{...C,marginBottom:8}}><div style={{marginBottom:8}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:3}}>Note</p><input value={note} onChange={e=>setNote(e.target.value)} placeholder="e.g. Tesco" style={{width:"100%",border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/></div><div style={{display:"flex",gap:7,alignItems:"flex-end"}}><div style={{flex:1}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:3}}>Date</p><input value={date} onChange={e=>setDate(e.target.value)} type="date" style={{width:"100%",border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/></div><button className="h" onClick={()=>setRecurring(!recurring)} style={{...B,padding:"7px 10px",borderRadius:8,fontSize:10.5,background:recurring?c.pg:"transparent",border:recurring?`2px solid ${c.p}`:`1.5px solid ${c.bd}`,color:recurring?c.p:c.sf}}>🔁</button></div></div>
      {txType==="expense"&&<div style={{...C,marginBottom:12}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:7}}>📸 Receipt</p>{!receiptPreview?<label style={{display:"flex",alignItems:"center",justifyContent:"center",gap:6,padding:"14px 0",border:`2px dashed ${c.bd}`,borderRadius:10,cursor:"pointer",color:c.sf,fontSize:11}}>📷 Tap to add<input type="file" accept="image/*" capture="environment" onChange={handleReceipt} style={{display:"none"}}/></label>:<div style={{position:"relative"}}><img src={receiptPreview} style={{width:"100%",maxHeight:200,objectFit:"cover",borderRadius:10}}/><button onClick={()=>{setReceiptFile(null);setReceiptPreview(null)}} style={{position:"absolute",top:6,right:6,...B,width:28,height:28,borderRadius:"50%",background:"rgba(0,0,0,0.6)",color:"#fff",fontSize:13}}>×</button><p style={{fontSize:9.5,color:c.inc,marginTop:6,textAlign:"center"}}>✅ Attached</p></div>}</div>}
      <button onClick={addTx} disabled={saving} className="h" style={{...B,width:"100%",padding:"13px 0",fontSize:13,borderRadius:14,background:saving?c.mu:`linear-gradient(135deg,${c.g1},${c.g2})`,color:"#fff",opacity:saving?0.7:1}}>{saving?"Saving...":"Save"}</button>
    </div>}

    {/* HISTORY */}
    {view==="history"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={()=>setView("home")} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><div><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>History</h2><p style={{fontSize:9.5,color:c.sf}}>{mLabel} · {mTx.length}</p></div></div><button className="h" onClick={exportCSV} style={{...B,background:c.pg,color:c.p,padding:"6px 10px",borderRadius:9,fontSize:10}}>📥</button></div>
      {mTx.length===0?<div style={{textAlign:"center",padding:30}}><p style={{fontSize:28}}>🔍</p></div>
      :<div style={{...C,padding:"3px 11px"}}>{mTx.map((tx,i)=>{const u=USERS.find(u=>u.id===tx.userId);return<div key={tx.id} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:i<mTx.length-1?`1px solid ${c.bd}`:"none"}}><span style={{width:32,height:32,borderRadius:9,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,flexShrink:0,background:tx.type==="income"?c.ig:c.eg}}>{tx.emoji}</span><div style={{flex:1,minWidth:0}}><div style={{display:"flex",alignItems:"center",gap:2}}><p style={{fontSize:11,fontWeight:500}}>{tx.category}</p>{tx.sg&&<span style={{fontSize:7,background:c.ag,color:c.ac,padding:"0.5px 3px",borderRadius:3.5,fontWeight:600}}>Split</span>}{tx.receiptUrl&&<span onClick={()=>setViewingReceipt(tx.receiptUrl)} style={{fontSize:9,cursor:"pointer",background:c.pg,padding:"1px 5px",borderRadius:4,color:c.p,fontWeight:600}}>📷</span>}</div><p style={{fontSize:8.5,color:c.mu,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{u?.avatar} {new Date(tx.date).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}{tx.note?` · ${tx.note}`:""}</p></div><p style={{fontSize:11.5,fontWeight:600,flexShrink:0,color:tx.type==="income"?c.inc:c.exp}}>{tx.type==="income"?"+":"−"}{fmt(tx.amount)}</p><button onClick={()=>startEdit(tx)} style={{...B,background:"none",fontSize:10,color:c.mu}}>✏️</button><button onClick={()=>setDelId(tx.id)} style={{...B,background:"none",fontSize:12,color:c.mu}}>×</button></div>})}</div>}
    </div>}

    {/* SEARCH */}
    {view==="search"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>{setView("home");setSearchQuery("");setSearchCat("all")}} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>🔍 Search</h2></div>
      <input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="Search..." style={{width:"100%",border:`1.5px solid ${c.bd}`,borderRadius:10,padding:"10px 12px",fontSize:12,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.card,marginBottom:10}} autoFocus/>
      <div style={{display:"flex",gap:4,marginBottom:12,overflowX:"auto",paddingBottom:4}}><button onClick={()=>setSearchCat("all")} style={{...B,padding:"5px 10px",fontSize:10,borderRadius:8,background:searchCat==="all"?c.pg:"transparent",border:searchCat==="all"?`2px solid ${c.p}`:`1px solid ${c.bd}`,color:searchCat==="all"?c.p:c.sf,whiteSpace:"nowrap"}}>All</button>{allCats.expense.map(ct=><button key={ct.name} onClick={()=>setSearchCat(ct.name)} style={{...B,padding:"5px 8px",fontSize:10,borderRadius:8,background:searchCat===ct.name?c.pg:"transparent",border:searchCat===ct.name?`2px solid ${c.p}`:`1px solid ${c.bd}`,color:searchCat===ct.name?c.p:c.sf,whiteSpace:"nowrap"}}>{ct.emoji}</button>)}</div>
      <p style={{fontSize:10,color:c.sf,marginBottom:8}}>{filteredTx.length} results</p>
      {filteredTx.length===0?<div style={{textAlign:"center",padding:20}}><p style={{color:c.sf,fontSize:11}}>No matches</p></div>
      :<div style={{...C,padding:"3px 11px"}}>{filteredTx.map((tx,i)=>{const u=USERS.find(u=>u.id===tx.userId);return<div key={tx.id} style={{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:i<filteredTx.length-1?`1px solid ${c.bd}`:"none"}}><span style={{width:32,height:32,borderRadius:9,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,background:tx.type==="income"?c.ig:c.eg}}>{tx.emoji}</span><div style={{flex:1,minWidth:0}}><p style={{fontSize:11,fontWeight:500}}>{tx.category}</p><p style={{fontSize:8.5,color:c.mu}}>{u?.avatar} {new Date(tx.date).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}{tx.note?` · ${tx.note}`:""}</p></div><p style={{fontSize:11.5,fontWeight:600,color:tx.type==="income"?c.inc:c.exp}}>{tx.type==="income"?"+":"−"}{fmt(tx.amount)}</p></div>})}</div>}
    </div>}

    {/* GOALS */}
    {view==="goals"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>setView("home")} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>🎯 Savings Goals</h2></div>
      <div style={{...C,marginBottom:12}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:8}}>New Goal</p><div style={{display:"flex",gap:5,marginBottom:8}}><input value={newGoalName} onChange={e=>setNewGoalName(e.target.value)} placeholder="e.g. Holiday" style={{flex:1,border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/></div><div style={{display:"flex",gap:5}}><input value={newGoalTarget} onChange={e=>setNewGoalTarget(e.target.value)} type="number" placeholder="Target £" style={{flex:1,border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/><button className="h" onClick={addGoal} style={{...B,background:c.p,color:"#fff",padding:"7px 14px",borderRadius:8,fontSize:11}}>Create</button></div></div>
      {goals.map(g=><div key={g.id} style={{...C,marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:12,fontWeight:600}}>{g.emoji} {g.name}</span><button onClick={()=>deleteGoal(g.id)} style={{...B,background:"none",fontSize:11,color:c.mu}}>×</button></div><div style={{height:8,background:c.bd,borderRadius:8,overflow:"hidden",marginBottom:6}}><div style={{height:"100%",borderRadius:8,background:g.saved>=g.target?c.inc:c.p,width:`${Math.min((g.saved/g.target)*100,100)}%`}}/></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:10,color:c.sf}}>{fmt(g.saved)} / {fmt(g.target)} {g.saved>=g.target?"🎉":""}</span><div style={{display:"flex",gap:4}}>{[10,25,50].map(n=><button key={n} className="h" onClick={()=>updateGoalSaved(g.id,n)} style={{...B,padding:"4px 8px",borderRadius:6,fontSize:9,background:c.pg,color:c.p}}>+£{n}</button>)}</div></div></div>)}
    </div>}

    {/* WISHLIST */}
    {view==="wishlist"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>setView("home")} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>💫 Wishlist</h2></div>
      <div style={{...C,marginBottom:12}}><div style={{display:"flex",gap:5,marginBottom:8}}><input value={newWishName} onChange={e=>setNewWishName(e.target.value)} placeholder="What do you want?" style={{flex:1,border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/></div><div style={{display:"flex",gap:5}}><input value={newWishPrice} onChange={e=>setNewWishPrice(e.target.value)} type="number" placeholder="Price £" style={{flex:1,border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/><button className="h" onClick={addWish} style={{...B,background:c.p,color:"#fff",padding:"7px 14px",borderRadius:8,fontSize:11}}>Add</button></div></div>
      {wishlist.map(w=>{const u=USERS.find(x=>x.id===w.addedBy);return<div key={w.id} style={{...C,marginBottom:6,padding:"12px 14px",opacity:w.done?0.5:1}}><div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={()=>toggleWish(w.id)} style={{...B,width:28,height:28,borderRadius:8,background:w.done?c.inc:"transparent",border:w.done?"none":`2px solid ${c.bd}`,color:"#fff",fontSize:12,display:"flex",alignItems:"center",justifyContent:"center"}}>{w.done?"✓":""}</button><div style={{flex:1}}><p style={{fontSize:12,fontWeight:500,textDecoration:w.done?"line-through":"none"}}>{w.emoji} {w.name}</p><p style={{fontSize:9,color:c.mu}}>{u?.avatar} {u?.name}{w.price?` · ${fmt(w.price)}`:""}</p></div><button onClick={()=>deleteWish(w.id)} style={{...B,background:"none",fontSize:12,color:c.mu}}>×</button></div></div>})}
    </div>}

    {/* REPORTS */}
    {view==="report"&&(()=>{const rd=reportData();const mx=Math.max(...rd.map(r=>Math.max(r.income,r.expense)),1);const ti=rd.reduce((s,r)=>s+r.income,0);const te=rd.reduce((s,r)=>s+r.expense,0);return<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>setView("home")} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>Reports</h2></div>
      <div style={{...C,marginBottom:10}}><h3 style={{fontSize:11.5,fontWeight:600,marginBottom:8}}>📈 Income</h3><BarChart data={rd.map(r=>({label:r.label,value:r.income}))} color={c.inc} maxVal={mx}/></div>
      <div style={{...C,marginBottom:10}}><h3 style={{fontSize:11.5,fontWeight:600,marginBottom:8}}>📉 Expenses</h3><BarChart data={rd.map(r=>({label:r.label,value:r.expense}))} color={c.exp} maxVal={mx}/></div>
      <div style={{display:"flex",gap:7}}><div style={{...C,flex:1,textAlign:"center",padding:"14px 10px"}}><p style={{fontSize:9,color:c.sf}}>6M Income</p><p style={{fontSize:16,fontWeight:700,fontFamily:"'Fraunces',serif",color:c.inc,marginTop:4}}>{fmt(ti)}</p></div><div style={{...C,flex:1,textAlign:"center",padding:"14px 10px"}}><p style={{fontSize:9,color:c.sf}}>6M Expenses</p><p style={{fontSize:16,fontWeight:700,fontFamily:"'Fraunces',serif",color:c.exp,marginTop:4}}>{fmt(te)}</p></div></div>
    </div>})()}

    {/* CONVERT */}
    {view==="convert"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>setView("home")} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>💱 Convert</h2></div>
      <div style={{...C,marginBottom:10,textAlign:"center",padding:"20px 16px"}}><input value={convAmt} onChange={e=>{setConvAmt(e.target.value);setConvResult(null)}} type="number" placeholder="100" inputMode="decimal" style={{fontSize:34,fontWeight:800,fontFamily:"'Fraunces',serif",border:"none",background:"transparent",textAlign:"center",color:c.tx,width:"80%"}}/></div>
      <div style={{...C,marginBottom:10}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:8}}>From</p><div style={{display:"flex",flexWrap:"wrap",gap:4}}>{CURRENCIES.map(cur=><button key={cur.code} onClick={()=>{setConvFrom(cur.code);setConvResult(null)}} style={{...B,padding:"5px 10px",fontSize:10.5,borderRadius:8,background:convFrom===cur.code?c.pg:(dark?c.ca:c.bd+"80"),color:convFrom===cur.code?c.p:c.sf,border:convFrom===cur.code?`2px solid ${c.p}`:"2px solid transparent"}}>{cur.flag} {cur.code}</button>)}</div></div>
      <div style={{textAlign:"center",marginBottom:10}}><button onClick={()=>{setConvFrom(convTo);setConvTo(convFrom);setConvResult(null)}} style={{...B,width:40,height:40,borderRadius:"50%",background:c.card,border:`1px solid ${c.bd}`,fontSize:16}}>🔄</button></div>
      <div style={{...C,marginBottom:12}}><p style={{fontSize:10.5,fontWeight:600,marginBottom:8}}>To</p><div style={{display:"flex",flexWrap:"wrap",gap:4}}>{CURRENCIES.map(cur=><button key={cur.code} onClick={()=>{setConvTo(cur.code);setConvResult(null)}} style={{...B,padding:"5px 10px",fontSize:10.5,borderRadius:8,background:convTo===cur.code?c.pg:(dark?c.ca:c.bd+"80"),color:convTo===cur.code?c.p:c.sf,border:convTo===cur.code?`2px solid ${c.p}`:"2px solid transparent"}}>{cur.flag} {cur.code}</button>)}</div></div>
      <button onClick={convert} disabled={convLoading||!convAmt} className="h" style={{...B,width:"100%",padding:"13px 0",fontSize:13,borderRadius:14,background:convLoading?c.mu:`linear-gradient(135deg,${c.g1},${c.g2})`,color:"#fff",marginBottom:12}}>{convLoading?"...":"Convert"}</button>
      {convResult&&<div style={{...C,textAlign:"center",padding:"20px 16px",borderLeft:`3px solid ${c.inc}`}}><p style={{fontFamily:"'Fraunces',serif",fontSize:30,fontWeight:800,color:c.inc}}>{CURRENCIES.find(x=>x.code===convTo)?.flag} {convResult.amount.toFixed(2)} {convTo}</p><p style={{fontSize:9,color:c.mu,marginTop:6}}>1 {convFrom} = {convResult.rate.toFixed(4)} {convTo}</p></div>}
    </div>}

    {/* SETTINGS */}
    {view==="settings"&&<div style={{padding:"16px 14px 105px",animation:"fi 0.2s"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:16}}><button onClick={()=>setView("home")} className="h" style={{...B,background:c.card,border:`1px solid ${c.bd}`,width:34,height:34,borderRadius:10,fontSize:14}}>←</button><h2 style={{fontFamily:"'Fraunces',serif",fontSize:18,fontWeight:700}}>Settings</h2></div>
      <div style={{...C,marginBottom:10}}><p style={{fontSize:11.5,fontWeight:600,marginBottom:8}}>🎨 Theme</p><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{Object.entries(THEMES).map(([k,t])=><button key={k} className="h" onClick={()=>changeTheme(k)} style={{...B,padding:"8px 12px",borderRadius:10,fontSize:10.5,background:`linear-gradient(135deg,${t.g1},${t.g2})`,color:"#fff",border:theme===k?"3px solid #fff":"3px solid transparent"}}>{t.name}</button>)}</div></div>
      <div style={{...C,marginBottom:10}}><p style={{fontSize:11.5,fontWeight:600,marginBottom:8}}>🏷️ Categories</p><div style={{display:"flex",gap:5,marginBottom:8}}><input value={newCatName} onChange={e=>setNewCatName(e.target.value)} placeholder="New category..." style={{flex:1,border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"7px 10px",fontSize:11.5,fontFamily:"'DM Sans',sans-serif",color:c.tx,background:c.bg}}/><button className="h" onClick={addCustomCat} style={{...B,background:c.p,color:"#fff",padding:"7px 12px",borderRadius:8,fontSize:11}}>Add</button></div>{(customCats.expense||[]).map(cc=><div key={cc.name} style={{display:"flex",justifyContent:"space-between",padding:"4px 0"}}><span style={{fontSize:11}}>{cc.emoji} {cc.name}</span><button onClick={()=>removeCustomCat("expense",cc.name)} style={{...B,background:"none",fontSize:11,color:c.exp}}>×</button></div>)}</div>
      <div style={{...C,marginBottom:10}}><p style={{fontSize:11.5,fontWeight:600,marginBottom:8}}>🔐 PIN</p>{storedPin?<div style={{display:"flex",gap:6}}><button className="h" onClick={()=>{setSettingPin(true);setNewPin("");setConfirmPin("")}} style={{...B,flex:1,padding:"8px 0",background:c.pg,color:c.p,fontSize:10.5,borderRadius:8}}>Change</button><button className="h" onClick={removePin} style={{...B,flex:1,padding:"8px 0",background:c.eg,color:c.exp,fontSize:10.5,borderRadius:8}}>Remove</button></div>:<button className="h" onClick={()=>{setSettingPin(true);setNewPin("");setConfirmPin("")}} style={{...B,width:"100%",padding:"8px 0",background:c.pg,color:c.p,fontSize:10.5,borderRadius:8}}>Set PIN</button>}</div>
    </div>}

    {/* EDIT MODAL */}
    {editingTx&&<div style={{position:"fixed",inset:0,background:dark?"rgba(0,0,0,0.5)":"rgba(0,0,0,0.28)",zIndex:999,display:"flex",alignItems:"center",justifyContent:"center",padding:16}} onClick={()=>setEditingTx(null)}><div style={{background:c.card,borderRadius:18,padding:22,maxWidth:300,width:"100%",animation:"pi 0.2s",border:`1px solid ${c.bd}`}} onClick={e=>e.stopPropagation()}><p style={{fontSize:14,fontWeight:600,marginBottom:12}}>✏️ Edit</p><div style={{marginBottom:10}}><p style={{fontSize:10,color:c.sf,marginBottom:3}}>Amount</p><input value={editAmt} onChange={e=>setEditAmt(e.target.value)} type="number" style={{width:"100%",border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"8px 10px",fontSize:13,color:c.tx,background:c.bg,fontFamily:"'DM Sans',sans-serif"}}/></div><div style={{marginBottom:10}}><p style={{fontSize:10,color:c.sf,marginBottom:3}}>Note</p><input value={editNote} onChange={e=>setEditNote(e.target.value)} style={{width:"100%",border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"8px 10px",fontSize:12,color:c.tx,background:c.bg,fontFamily:"'DM Sans',sans-serif"}}/></div><div style={{marginBottom:14}}><p style={{fontSize:10,color:c.sf,marginBottom:3}}>Date</p><input value={editDate} onChange={e=>setEditDate(e.target.value)} type="date" style={{width:"100%",border:`1.5px solid ${c.bd}`,borderRadius:8,padding:"8px 10px",fontSize:12,color:c.tx,background:c.bg,fontFamily:"'DM Sans',sans-serif"}}/></div><div style={{display:"flex",gap:6}}><button onClick={()=>setEditingTx(null)} style={{...B,flex:1,padding:"10px 0",background:c.bd,color:c.tx,fontSize:12,borderRadius:10}}>Cancel</button><button onClick={saveEdit} style={{...B,flex:1,padding:"10px 0",background:`linear-gradient(135deg,${c.g1},${c.g2})`,color:"#fff",fontSize:12,borderRadius:10}}>{saving?"...":"Save"}</button></div></div></div>}
    {viewingReceipt&&<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",zIndex:1001,display:"flex",alignItems:"center",justifyContent:"center",padding:16}} onClick={()=>setViewingReceipt(null)}><div style={{maxWidth:360,width:"100%"}} onClick={e=>e.stopPropagation()}><button onClick={()=>setViewingReceipt(null)} style={{...B,width:32,height:32,borderRadius:"50%",background:"rgba(255,255,255,0.2)",color:"#fff",fontSize:16,marginBottom:8,marginLeft:"auto",display:"block"}}>×</button><img src={viewingReceipt} style={{width:"100%",borderRadius:14}}/></div></div>}
    {delId&&<div style={{position:"fixed",inset:0,background:dark?"rgba(0,0,0,0.5)":"rgba(0,0,0,0.28)",zIndex:999,display:"flex",alignItems:"center",justifyContent:"center",padding:16}} onClick={()=>setDelId(null)}><div style={{background:c.card,borderRadius:18,padding:22,maxWidth:260,width:"100%",animation:"pi 0.2s",textAlign:"center",border:`1px solid ${c.bd}`}} onClick={e=>e.stopPropagation()}><p style={{fontSize:28,marginBottom:6}}>🗑️</p><p style={{fontSize:13,fontWeight:600,marginBottom:14}}>Delete?</p><div style={{display:"flex",gap:6}}><button onClick={()=>setDelId(null)} style={{...B,flex:1,padding:"9px 0",background:c.bd,color:c.tx,fontSize:11,borderRadius:10}}>Keep</button><button onClick={()=>delTx(delId)} style={{...B,flex:1,padding:"9px 0",background:c.exp,color:"#fff",fontSize:11,borderRadius:10}}>Delete</button></div></div></div>}

    <div style={{position:"fixed",bottom:0,left:"50%",transform:"translateX(-50%)",width:"100%",maxWidth:480,background:dark?"rgba(13,13,20,0.92)":"rgba(244,241,234,0.92)",backdropFilter:"blur(16px)",borderTop:`1px solid ${c.bd}`,display:"flex",justifyContent:"space-around",alignItems:"center",padding:"4px 0 8px",zIndex:100}}>
      <button className="h" onClick={()=>setView("home")} style={{...B,background:view==="home"?c.pg:"transparent",padding:"5px 13px",borderRadius:10,fontSize:10,color:view==="home"?c.p:c.mu}}><div style={{textAlign:"center"}}><div style={{fontSize:16}}>🏠</div>Home</div></button>
      <button onClick={()=>{setView("add");setTxType("expense");reset()}} style={{...B,width:50,height:50,borderRadius:"50%",background:`linear-gradient(135deg,${c.g1},${c.g2})`,color:"#fff",fontSize:24,transform:"translateY(-8px)",boxShadow:`0 4px 14px ${c.g1}44`}}>+</button>
      <button className="h" onClick={()=>setView("history")} style={{...B,background:view==="history"?c.pg:"transparent",padding:"5px 13px",borderRadius:10,fontSize:10,color:view==="history"?c.p:c.mu}}><div style={{textAlign:"center"}}><div style={{fontSize:16}}>📋</div>History</div></button>
    </div>
  </div>);
}
